language: elixir

dist: trusty
sudo: required

services:
  - docker

otp_release: '21.2'

elixir: '1.8'

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.1
    - CASSANDRA_VERSION=3
    - SCYLLA_VERSION=2.3.0

jobs:
  include:
    - stage: test
      script: mix test
      before_script:
        - docker-compose --file docker-compose.yml --file docker-compose.cassandra.yml up -d
        - ./test/docker/health-check-services.sh

    - elixir: '1.4'
      otp_version: '19.3'

    - env: CASSANDRA_VERSION=3 AUTHENTICATION=true

    - env: CASSANDRA_VERSION=2.2

    - env: CASSANDRA_VERSION=2.2 AUTHENTICATION=true

    - stage: test scylla
      script: mix test --exclude cassandra_specific
      before_script:
        - docker-compose --file docker-compose.yml --file docker-compose.scylla.yml up -d
        - ./test/docker/health-check-services.sh

    - elixir: '1.4'
      otp_version: '19.3'

    - env: SCYLLA_VERSION=2.3.0 AUTHENTICATION=true
    
    - env: SCYLLA_VERSION=2.0.0

    - env: SCYLLA_VERSION=2.0.0 AUTHENTICATION=true

    - stage: check formatted
      script: mix format --check-formatted
      before_install: skip
      sudo: false
      env: null

stages:
  - check formatted
  - test
  - test scylla

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) > docker-compose
  - chmod +x docker-compose